name: tp-final-ngs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::multiqc
  - bioconda::fastqc
  - bioconda::star
  - conda-forge::biopython
  - bioconda::qualimap
  - bioconda::deeptools
  - bioconda::samtools
