name: tp-final-ngs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::multiqc
  - bioconda::fastqc
  - biconda::star
  - conda-forge::biopython